version: "3.1"
services:
  db:
    image: postgres:16.2-alpine3.19
    volumes:
      - db-data-16:/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432/tcp
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
  web:
    image: odoo:17.0
    container_name: odoo17
    depends_on:
      - db
    ports:
      - "9090:8069/tcp"
    tty: true
    command: -- --dev=reload
    volumes:
      - web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
volumes:
  db-data-16:
    driver: local
  web-data:
    driver: local
