name: 🚀 Format and Lint
on: [push, pull_request]

jobs:
  format-and-lint:
    name: ✅ Format and Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.11
    steps:
    - uses: actions/checkout@v2

    - name: 🌴 Install python
      uses: gabrielfalcao/pyenv-action@v8
      with:
        default: "${{ matrix.python }}"
        command: pip install -U pip

    - name: 🚀 Install dependencies
      run: |
          pip install --disable-pip-version-check -r dev.requirements.txt

    - name: 🧪 Run format and lint
      run: |
          make format && make lint